package postgre

import (
	"context"
	"decadecollab/internal/config"
	"decadecollab/internal/models"
	"fmt"

	"github.com/jackc/pgx/v5"
)

//logger sdelai :-)
func DBConn(cfg config.PSQLConfig) (*pgx.Conn,error){
	usr := cfg.Username
	pass := cfg.Password
	db := cfg.Database
	port := cfg.Port
	strConn := fmt.Sprintf("postgres://%s:%s@localhost:%s/%s",usr,pass,port,db)
	
	conn,err := pgx.Connect(context.Background(),strConn)
	if err != nil {
        return nil, fmt.Errorf("failed to connect to database: %w", err)
    }
	return conn,nil
}
//sdelai logger :D
func CreateUsersTable(conn *pgx.Conn) error {
    query := `
    CREATE TABLE IF NOT EXISTS users (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        password VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
    );
    `
    _, err := conn.Exec(context.Background(), query)
    if err != nil {
        return fmt.Errorf("failed to create users table: %w", err)
    }
    
    return nil
}
//add logger :)
func CreateUser(username string,password string,email string)(int,error){
	conn,_ := DBConn()
 	query := "INSERT INTO users (name,password,email) values($1,$2.$3) RETURNING id"
	var id int
	err := conn.QueryRow(context.Background(),query,username,password,email).Scan(&id)
	if err != nil {
        return 0,fmt.Errorf("failed to add user: %w", err)
    }
	return id,nil
}
//dobav' logger :-D
func UpdateUser(id int,username string,password string,email string)error{
	conn,_ := DBConn()
	query := "UPDATE users SET name = $1,password = $2, email = $3 where id = $4"

	_,err := conn.Exec(context.Background(),query,username,password,email,id)
	if err != nil {
        return fmt.Errorf("failed to create users table: %w", err)
    }
	return nil
}
// logger namuti :-)
func DeleteUser(id int)error{
	conn,_ := DBConn()
	query := "DELETE FROM users WHERE id = $1"

	_,err := conn.Exec(context.Background(),query,id)
	if err != nil{
		return fmt.Errorf("user not found: %w", err)
	}
	return nil
}
//dai logger :*
func GetUSer(id int) (*models.User,error){
	conn,_ := DBConn()
	var user models.User
	query := "SELCT * FROM users WHERE id = $1"

	err := conn.QueryRow(context.Background(),query,id).Scan(&user.Id,&user.Username,&user.Password,&user.Email)
	if err != nil{
		return nil,fmt.Errorf("user not found: %w", err)
	}
	return &user,err
}